cookie:
  expiry_days: 0
  key: random key
  name: lil cookie
credentials:
  usernames:
    admin:
      email: echina725@gmail.com
      name: Guilherme China
      password: $2b$12$BYOE3mmqvAsO4MLFAUCjmuN0jNqSNGDw7CzesvH7AunzscoROzroy
    general:
      email: johndoe@email.com
      name: general user
      password: $2b$12$F91s7k69iTm5likjBRInkeVpx75w1g3IpXVAzUWKwCFV0rcy87zLC
preauthorized:
  emails:
  - echina725@gmail.com
